In [3]:
import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv(r'anime.csv')

In [5]:
df.head()

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

In [6]:
df.loc[2]['Title']

'Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 - Dec 2022474,138 members'

In [7]:
def extract_episodes(txt):
    check = False
    data = ""
    for i in txt:
        if i == ")":
            check = False
            return data
        if check == True:
            data == data + i
        if i == '(':
            check = True

In [8]:
df["Episodes"] = df["Title"].apply(extract_episodes)

In [9]:
df["Episodes"] = df["Episodes"].str.replace(" eps", "", regex=False)

In [10]:
df["Episodes"] = pd.to_numeric(df["Episodes"], errors="coerce")

In [11]:
df["Episodes"] = df["Episodes"].fillna(0).astype(int)

In [12]:
df.head()

   Rank                                              Title  Score  Episodes
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10         0
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07         0
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06         0
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06         0
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05         0

In [13]:
df.loc[3]['Title']

'Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 members'

In [18]:
def extraction_time(txt):
    check = False
    data = ""
    for i in range(len(txt)):
        if txt[i] == ')':
            for j in range(i+1,i+18):
                data += txt[j]

            return data

In [19]:
df['Title'] = df['Title'].apply(extraction_time)

In [20]:
df.head()

   Rank              Title  Score  Episodes
0     1  Apr 2009 - Jul 20   9.10         0
1     2  Apr 2011 - Sep 20   9.07         0
2     3  Oct 2022 - Dec 20   9.06         0
3     4  Apr 2015 - Mar 20   9.06         0
4     5  Apr 2019 - Jul 20   9.05         0

In [22]:
df[df['Score'] == df['Score'].max()]['Title']

0    Apr 2009 - Jul 20
Name: Title, dtype: object

In [23]:
df['Score'].unique()

array([9.1 , 9.07, 9.06, 9.05, 9.04, 9.03, 9.02, 8.99, 8.98, 8.94, 8.93,
       8.91, 8.89, 8.88, 8.87, 8.84, 8.83, 8.82, 8.81, 8.8 , 8.79, 8.78,
       8.77, 8.76, 8.75, 8.74, 8.73, 8.72, 8.71])